NCIOCPL/wcms-front-end

tools/build/build-release.sh
Address an issue with branch names becoming ambiguous by changing the automatic tag name to end in "-latest".
=> Differentiate tag name from branch.

tools/build/setup.job
Work on the build script during pilfering-penguin included changes to create_branch_skeleton.job, requiring setup.job to reference pilfering-penguin instead of master.  This reverts to loading create_branch_skeleton.job from master.
=> Load create_branch_skeleton from master

.gitignore, CancerGov/server/mock_views/mock_example.html, CancerGov/server/server.js
This should not cause any issues in production. Node runs a simple env test and, only in development, exposes /mock/ routes which allow us to us a mock_views folder as a bucket for HTML editing and mockups with automated routing (based on filename).  
This means we don't have to build mock routing every time and worry about clean up before merging back in to the main branch. The mock_views bucket contents are excluded from git (excepting the example file).
As a bonus, if you got to localhost:3000/mock there is a doc page that will test your faith in humanity!
=> Mock views dev proxy router

CancerGov/_src/StyleSheets/AppModuleSpecific/cts/_cts.advanced.scss
At very small mobile breakpoints, text would occasionally push table out to accommodate those nasty words like immunogobugloboparisis. Now we can treat them like kit kat bars. 
Give me a break, give me a break, break me off a piece of that sarcoidemenahalitosis!
=> [WCMSFEQ-786] Word-break added at sm bp

.gitignore
Now we have a merry little bucket for all those dusty old mock views to accumulate in. Clean your code and your attic!
=> Mock views are no longer ignored by git

CancerGov/_src/StyleSheets/AppModuleSpecific/cts/_cts.advanced.scss, CancerGov/_src/StyleSheets/AppModuleSpecific/cts/_cts.basic.scss
Fixing placement of Start Over text when there is no criteria box. Fixing placement of text-icon-help in Safari which is a bug on Production currently.
=> WCMSFEQ-804--fali

CancerGov/grunt/webpack.js, CancerGov/package.json, CancerGov/webpack.config.js
NO CONTENT/CMS CHANGES
I've added several new webpack features to massively reduce build times (~21s -> ~6s):
--UglifyJS is updated to a version that supports a parallel build process
--HappyPack was added to parallelize JS and CSS module building (awesome-typescript-loader does not work with happypack though ts-loader does using another library and an extra step)
--HardSourceWebpackPlugin was added to cache builds (this made by far the biggest impact)
--source mapping changed from 'source-map' to 'eval-source-map', which is faster anyway but also helps optimize the way HardSource works.
Side note, Babel-Polyfill was removed as an entry point since Frank had just moved the pertinent parts into InnerPage.js
=> [WCMSFEQ-903] Webpack updates for increased build speeds.

CancerGov/_src/Scripts/NCI/Modules/accordion/_accordion.scss
Margin was being set on either side to -32px to break out of .row class and go fullscreen. Changed to -30px.
=> [WCMSFEQ-904] Fixed CTHP Accordion overflow

CancerGov/_src/PageTemplates/includes/TemplateIntro.inc, CancerGov/_src/Scripts/NCI/Modules/megamenu/_megamenu.scss, CancerGov/_src/Scripts/NCI/UX/Common/Common.js
Removing preload strategy for CSS because IE. 
Adding IE polyfills for ES6.
Adjusting main menu padding due to updated font widths
=> IE Patches

CancerGov/release_notes/frontend-2018-02-23.md
No Manual Changes
NOTE: The TermDictionaryWidgetInnards.js file needs to be uploaded during this release. It is now being processed through the grunt uglify tasks.
=> [WCMSFEQ-887] Dictionary Widget update AMEND

CancerGov/_src/Scripts/NCI/UX/PageSpecific/CTHP/CTHPPage.scss
[WCMSFEQ-979] The CTHP cards are overlapping each other on IE-11
ie flexbox fix
=> CTHP Overlapping cards fix (IE11)

CancerGov/_src/Scripts/NCI/Modules/cthpDropdown/index.scss, CancerGov/_src/StyleSheets/nvcg.scss, CancerGov/release_notes/frontend-2018-07-20-july-sprint.md
Issues with CSS Nano minifying z-indexes (which is a known issue with the library and targeted for a bugfix in the next release) means when z-indexes exist in two different stylesheets they are unpredictable. For now, it means overrides will have to be in a common file to both rules (so moving the z-index rule from CTHP to nvcg where the video thumbnail rules are fixes it).
=> [WCMSFEQ-1029] CTHP Dropdown Z-index fix

CancerGov/_src/Scripts/NCI/UX/PageSpecific/CTHP/CTHPPage.scss, CancerGov/release_notes/frontend-2018-07-20-july-sprint.md
Sometime in the long yesterwhen, a simple stake holder had a dream. A dream of accordions. It went back to the long summer she had spent studying abroad in Paris. Bike rides along the seine, baguettes and wine at the top of Montmartre, and especially the buskers in oversized pantaloons outside the Centre Pompidou heaving away on their tired but melodious music boxes. She brought this dream to work and saw how it could inspire new heights of user experience. A responsive website for a new internet. And so she gave a developer purpose when she tasked him with bringing her dream to life. The developer had never experienced the dizzying heights of Paris, but he was very familiar with the dizzying lows of Javascript in the prehistory of ES3. And so he sat and hacked and sawed and sweated …
=> [WCMSFEQ-982]  Fix missing video thumbnail at mobile on CTHP

CancerGov/_src/Scripts/NCI/UX/PageSpecific/BlogPost/BlogPostPage.ts, CancerGov/_src/Scripts/NCI/UX/PageSpecific/BlogSeries/BlogSeriesPage.js, CancerGov/_src/Scripts/NCI/Utilities/domManipulation.js, CancerGov/release_notes/frontend-2018-07-20-july-sprint.md
The manual moving around of the page options on Blog Pages was not syncing between the JS and CSS ways of reading window width. Changing the code to use matchMedia instead solves this. I also refactored the changed code into a utility function as it was being replicated across Blog Post and Blog Series Page types.
=> [WCMSFEQ-740] Add Blog PageOptions Transporter Utility Function

CancerGov/_src/Scripts/NCI/UX/PageSpecific/Inner/Enhancements/directory-search-results.js, CancerGov/_src/Scripts/NCI/UX/PageSpecific/Inner/InnerPage.scss, CancerGov/_src/Scripts/NCI/UX/PageSpecific/Inner/InnerPage.ts, CancerGov/_src/StyleSheets/_directory-search.scss, CancerGov/release_notes/frontend-2018-07-20-july-sprint.md
There are multiple problems with this form. New CSS (_directory-search.scss) and JS (directory-search-results.js) have been added to correct the form behavior and to add the new feature of preserving checkbox selections between page results. This is done in a similar manner to CTS search results where the checked items are store in Session Storage.
Accessibility issues include:
1. No submit button on the form - form cannot be submitted using standard keyboard controls
2. Checkbox labels are also `<a>` tags so clicking on them sends the user to a new page
There's also an inline `<script>` block adding (global) form submission functions. These should also be removed in a CDE release because we'll want to control this from the front-end codebase.
I'm running some JavaScript DOM manipulation …
=> [WCMSFEQ 665]  genetics directory form selections

CancerGov/_src/SublayoutTemplates/SubLayout_Guide_With_Title.ascx, CancerGov/release_notes/frontend-2018-07-20-july-sprint.md
For whatever reason, .collapse was added to the container div for Guide Card titles. I say whatever because it seems to have no effect except to remove the desired padding at all breakpoints. There is still a CSS rule manually hiding the title itself. So removing this class had no apparent, deleterious effect except to restore the padding. This change requires uploading all the templates again and republishing CDE (but we do that anyway on every release).
Any unforeseen side effects you can predict without deploying the templates again?
=> [WCMSFEQ-939] Guide Card Title Alignment Fix

CancerGov/_src/Scripts/NCI/UX/Common/Common.js, CancerGov/_src/Scripts/NCI/UX/Common/polyfills/replaceWith.js, CancerGov/_src/Scripts/NCI/UX/PageSpecific/Inner/Enhancements/directory-search-results.js
Adding IE polyfill
Updating form submission to use `window.location` instead of `form.submit()` since the form submit is passing both the querystring and the form values resulting in duplicate requests for items.
=> [WCMSFEQ-665] Bugfixes for Genetics Directory Search

CancerGov/_src/Scripts/NCI/UX/Common/Common.js
The sortable tables are showing a strange behaviour on IE11 that may be due to the lack of said method. This polyfill will hopefully alleviate that (it's not a problem on dev, which means it's not possible to determine without a deploy. Either way, this is a useful polyfill to have available going forward).
=> [WCMSFEQ-1041] Add Array.find polyfill for ie11

DCEG/Stylesheets/layout-print.css
The previous font-size increase change caused overflow/cutoff issues that this remedies.
=> [WCMSFEQ-1071] FIXUP Adding rules to prevent print page cutoffs

DCEG/Stylesheets/baseline-print.css
Remove font size set in .genSiteContainer which was adding on top of the body size.
=> Fixup  wcmsfeq 1071  fix print fontsize

CancerGov/_src/Scripts/NCI/Modules/pageOptions/types/email.js, CancerGov/release_notes/frontend-2018-08-22-august-sprint.md
Links with query params were not embedding correcting in pageOptions mailto href links. This fix corrects that by encoding the links with encodeURIComponent and the surrounding text with encodeURI.
=> [WCMSFEQ-1088]  PageOptions email mailto fix

CancerGov/_src/Scripts/NCI/UX/PageSpecific/PDQ/pdqcis.js, CancerGov/release_notes/frontend-2018-08-22-august-sprint.md
In order to meet the current requirement for social sharing via page options, we need to stop updating the og:url with hash paths. 
In addition, deprecated code related to the old page options email sharing link was removed as cleanup.
NO CONTENT CHANGES.
=> [WCMSFEQ-1096]  Stop updating the og:url from PDQ router

CancerGov/_src/Scripts/NCI/Modules/forms/formControls.js, CancerGov/_src/Scripts/NCI/UX/Common/Common.js, CancerGov/_src/Scripts/NCI/UX/Common/Enhancements/jQueryUIExtensions.js, CancerGov/release_notes/frontend-2018-08-22-august-sprint.md
The crux of the problem was that the extension that was created to obviate the accessibility issues was loading after the first pass of the selectmenu plugin. Fixing the issue only required flipping the order of execution.
However, to avoid similar issues in the future as well as to continue our efforts towards cleaning up Common.js, I have moved all the jquery UI extension scripts into their own file, which can be pulled in right after jquery itself and before any other modules (which may utilize jQuery UI) have a chance to execute.
=> [WCMSFEQ-1091]  jQuery-ui.selectmenu accessibility fix

CancerGov/_src/Scripts/NCI/UX/PageSpecific/Inner/InnerPage.scss, CancerGov/_src/StyleSheets/_font_resizer.scss, CancerGov/release_notes/frontend-2018-08-22-august-sprint.md
Some App Module pages only receive the InnerPage template and provide no simple way to disable features that are required on other Inner Pages (such as those used for content). Because an appmodule specific class is added to the body element, we can use that to implement a hack to hide the font resizer using CSS.
=> [WCMSFEQ-1086] Disable Font Resizer on App Module Pages

CancerGov/_src/Scripts/NCI/Modules/pageOptions/types/facebook.js, CancerGov/_src/Scripts/NCI/Modules/pageOptions/types/googleplus.js, CancerGov/_src/Scripts/NCI/Modules/pageOptions/types/pinterest.js, CancerGov/_src/Scripts/NCI/Modules/pageOptions/types/twitter.js, CancerGov/release_notes/frontend-2018-08-22-august-sprint.md
The page options getContent utility function logs a warning when a piece of content does not have a translation in the desired language and is falling back to the English default. In the case of trademarked names like Google and Facebook, no translation is necessary so the fall.back works. However, to alleviate concerns about seeing warnings on Spanish pages in the console, I'm provided redundant Spanish translations to stop the warning from appearing.
=> [WCMSFEQ-1081] Hide Page Options Warnings on Spanish Pages

CancerGov/_src/Scripts/NCI/UX/Common/Enhancements/analytics.js, CancerGov/release_notes/frontend-2018-08-22-august-sprint.md
A few years ago the class being attached to the main NCI logo and the analytics function hooking into it got out of sync. This change is just pointing the existing analytics function at the correct selector.
=> [WCMSFEQ-1098] Hotfix to NCI logo analytics

CancerGov/_src/StyleSheets/_general.scss, CancerGov/release_notes/frontend-2018-08-22-august-sprint.md
On some spanish pages in IE only, a white line is appearing at the very bottom of the page (below the footer).  It seems to be an issue with the <sup>®</sup> and it having a CSS reset style of vertical-align: baseline. Added vertical-align: text-top the <sup> element to overwrite this and remove white line at the bottom of the page. NO CONTENT CHANGES.
=> [WCMSFEQ-980] Fix issue with white line in footer on IE 11

CancerGov/_src/StyleSheets/AppModuleSpecific/cts/_cts.basic.scss, CancerGov/release_notes/frontend-2018-08-22-august-sprint.md
When printed, the basic CTS pages were missing a border around the fieldset headers (for Cancer Type/Keyword, Age, and U.S. Zip Code) due to the fieldsets using a background color on the page  - background colors do not get printed.  The help icons appeared to be off-center due to the missing background color.  Added a print media query to _cts.basic.scss with a background border for the fieldset legends, and aligned the help icon to the vertical center of the fieldset.
=> [WCMSFEQ-932] Fix for Basic CTS Printed Pages Missing Borders

CancerGov/_src/StyleSheets/_topicFeature.scss, CancerGov/release_notes/frontend-2018-september-sprint.md
The text in the inline feature cards was too large for the space, which caused most lines to break to one word. The H3 and p font sizes were reduced, along with a slight line-height and color change.
=> [WCMSFEQ-1119] Change inline feature card font style attributes

CancerGov/_src/Scripts/NCI/Modules/nav/sectionmenu.js, CancerGov/release_notes/frontend-2018-september-sprint.md
At 1024px breakpoint, the Section Menu was defaulting to an open state and showing the submenu that it contains.  This was occurring on every page that invokes the Section Menu Nav button, not just the Cancer Currents Blog page.
* Set min-width for the section menu resizeHandler to 1025px to prevent the section menu navigation from defaulting to open at the 1024px breakpoint
=> [WCMSFEQ-1079] Blue bar on cancer currents blog page

CancerGov/_src/StyleSheets/AppModuleSpecific/cts/_cts.basic.scss, CancerGov/release_notes/frontend-2018-september-sprint.md
The help-icon was overlapping the Type/Condition heading label at the 326px breakpoint and lower.
* Changed padding-right of fieldset legend to 43px to prevent icon overlapping text
=> [WCMSFEQ-909]  Help link overlapping blue heading label

CancerGov/_src/VelocityTemplates/CTSDrawLocations.inc, CancerGov/release_notes/frontend-2018-september-sprint.md
Provider emails were appearing next to the phone number (rather than on the following line) under Locations and Contacts accordion:
* added <br> to Email line in CTSDrawLocations include file
=> [WCMSFEQ-914]  Provider emails appearing next to phone number

CancerGov/_src/Scripts/NCI/Modules/megamenu/_megamenu.scss, CancerGov/release_notes/frontend-2018-september-sprint.md
The goal of this request is to enhance the usability of the megamenu by removing the scrollbar. 
* Removed the mega-menu-scroll class and set subnav max open height to 450px
* Updated font size and line height for submenu list items and titles
* Re-adjusted subnav max open height to 460px and line height of sub-nav-mega class to 1.1em to accomodate largest spanish mega menu list items
=> [WCMSFEQ-1128]  Remove scroll bar from megamenu

CancerGov/_src/Scripts/NCI/UX/Common/Enhancements/charts.js, CancerGov/release_notes/frontend-2018-september-sprint.md
Allows lazy loading of Highmaps when the necessary chart type is defined in Fact Book pages
Note: Nothing testable until about-nci/budget/fact-book/extramural-programs/grant-contract-awards is updated
=> [Wcmsfeq-1043] highmaps support

CancerGov/_src/StyleSheets/_mainContent.scss, CancerGov/_src/StyleSheets/_nav.scss, CancerGov/release_notes/frontend-2018-september-sprint.md
The absolutely positioned section nav was behaving differently in Safari. This change adds a position relative rule to the main-content container and realigns the section nav relatie to that, for a more standardized approach.
=> [WCMSFEQ-1163]  Fix section nav alignment bug in Safari

CancerGov/_src/Scripts/NCI/Modules/megamenu/_megamenu.scss, CancerGov/release_notes/frontend-2018-september-sprint.md
updated right margin of sub-nav-mega ul to 3% to increase space between columns in the megamenu list
=> [WCMSFEQ-1128] Remove-scroll-bar-from-megamenu2

CancerGov/_src/StyleSheets/AppModuleSpecific/cts/_cts.advanced.scss, CancerGov/release_notes/frontend-2018-september-sprint.md
Added word-wrap to locationBlock class to prevent email addresses from being cut off (and not visible) at 511px bp and lower
=> fixup! [WCMSFEQ-914] Provider emails appearing next to phone number

CancerGov/_src/StyleSheets/_mainContent.scss, CancerGov/release_notes/frontend-2018-september-sprint.md
Moved the relative positioning from main-content div to general-page-body-container to correctly target the section-menu-button and underlying overlay div
=>  fixup! [WCMSFEQ-1163]  Fix section nav alignment bug in safari2

CancerGov/package-lock.json, CancerGov/package.json, CancerGov/release_notes/FEQ-oct2018-release.md
At some point SWS stopped working on localhost. Turns out, recent (annoyingly undocumented) updates to the proxy library dependency version we were already using (express-http-proxy) fix this issue without any other code changes being necessary. (Under the hood, they improved their handling of non-GET http requests: SWS uses a POST).
=> [WCMSFEQ-699]  Fix sitewidesearch proxy for localhost environments

CancerGov/_src/Scripts/NCI/Modules/megamenu/megamenu.js, CancerGov/_src/Scripts/NCI/Vendor/jquery-accessibleMegaMenu.js, CancerGov/release_notes/FEQ-oct2018-release.md, CancerGov/webpack.config.js, package-lock.json
Since it's inception, there has been a bug in the megamenu that caused certain pieces of functionality to not be added to the module on instantiation at screen sizes below 1024px. This fix conditionally creates a self-expiring (cue the Mission Impossible theme song) media listener that will let the existing megamenu instance rerun it's setup functions when a user goes from tablet to desktop size for the first time. 
In addition, the throttle-debounce dependency was used and as such updated, so the package-lock is updated as well.
=> [WCMSFEQ-1159]  Patch to fix megamenu bug on resize

CancerGov/_src/Scripts/NCI/UX/Themes/purple/purple.scss
Cleaning up some desktop styles so theme is more mobile-first. Nesting more selectors so it's easier to scan style blocks. Redoing `.mobile-menu-bar` to use flexbox. Assigning more hex colors to variables.
=> [WCMSFEQ-1251] Multiple fixes to the mobile-first styles and sass syntax

CancerGov/_src/Scripts/NCI/UX/Common/Enhancements/analytics.js
The global change of the CTHP card headers from H3's to H2's was not reflected in the analytics.
=> [WCMSFEQ-1300]  Prop57 not firing on CTHP cards

CancerGov/_src/Scripts/NCI/Modules/videoPlayer/flex-video-api.js
remove initialize variable that prevents reinitialization
=> [WCMSFEQ-1296] Video Carousel Hotfix

CancerGov/_src/Scripts/NCI/Modules/modal/_modal.scss, CancerGov/_src/Scripts/NCI/UX/Common/Enhancements/popup_functions.js
1. Are we fixing iPhone and mobile breakpoint issues in this release? (WCMSFEQ-1325)
2. Do we want the terms in uppercase in the Modals (commented in the ticket 585)
3. For Inline Feature Cards , the image size appears different on DT than Prod. Why?
4. Underline appears broken in Modals for some letters....we have a ticket for awareness (cannot fix now)
5. Close button has different font size and style than CTS...asked Michelle to take a look
6. Can we request Chuck or Michelle to verify if image caption in modal looks good to them?
7. The Spanish modals says Definition in place of Definición
=> QA Feedback round 1

CancerGov/_src/Scripts/NCI/UX/PageSpecific/PDQ/PDQPage.scss, CancerGov/_src/Scripts/NCI/Utilities/domManipulation.js
[WCMSFEQ-1344] Accordion clearfix
When the accordion is initialized on a PDQ page (on mobile only) it kicks off a number of classes, including a clearfix. When the accordion is removed (resize your browser up to tablet or desktop) all the classes except clearfix are removed.  This lingering clearfix caused. an extra 10px of spacing in-between PDQ sections.  Hence, the clearfix class was set to display: none, (and the content was also set to none to be double-safe that content with an empty string isn't generated) at tablet breakpoint and higher. 
[WCMSFEQ-1345] Not seeing the padding above each H2 on IE
On IE, the padding between H2 sections were not displaying.  This is because within domManipulation.js, querySelectorAll forEach was being used to iterate over an array. …
=> [WCMSFEQ-1344] [WCMSFEQ-1345]  IE Padding and clearfix fixes

CancerGov/_src/Scripts/NCI/Modules/linkAudioPlayer/linkAudioPlayer.js, CancerGov/release_notes/FEQ-february2019-backlog-release.md
Link audioplayer currently looks only at the href attribute of an anchor to determine the file pathname. On the CDR, this is insufficient and the library needs to also append the search attribute as well. This change support the two methods of retrieving the path to the audiofile.
=> [WCMSFEQ-1274]  Add support for CDR in linkAudioPlayer

CancerGov/_src/Scripts/NCI/Modules/modal/_modal.scss, CancerGov/release_notes/FEQ-february2019-backlog-release.md
Style change to remove capitalization of first letters for dictionary terms in modal windows
=> Wcmsfeq 1343  remove capitalization dictionary terms modal

CancerGov/_src/StyleSheets/_tableSort.scss, CancerGov/release_notes/FEQ-february2019-backlog-release.md
[WCMSFEQ-1338] Sortable Tables Header Row is Broken
The Sortable Tables header row was broken on all breakpoints due to the load order of the svg-sprite. Cleaned up the sortable table styling to remove the unnecessary positioning, add annotations, as well as updated the footer and mobile styles.  
[WCMSFEQ-1303] The first column header
For sortable tables, the first column (header and corresponding table cells) were misaligned, and (in some tables) sorting the first column makes it appear as tiles.  This is a known bug (and limitation of the use of tables) and occurs when the content in some column cells exceed the height of the first.  On mobile, the height was set at 200px, which accomodates most content sizing.  This cannot be set as auto, or inherit, because a table row cannot inherit …
=> [WCMSFEQ-1338]  Sortable tables header row

CancerGov/release_notes/FEQ-february2019-backlog-release.md, DCEG/Stylesheets/baseline.css
[WCMSFEQ-1322] [Change Request] DCEG Video Player Padding
Inline video player on DCEG (set to left or right) had a forced zero-set left margin, so content was flush against the video player.  Created two video classes (video-lft and video-rt) to adopt the same 41.75px margins currently implemented on cancergov.  Removed the zero left margin from all three existing video size classes (.size50, .size75, and .size100).
=> [WCMSFEQ-1322]  DCEG video player padding

CancerGov/_src/Scripts/NCI/Modules/carousel/_carousel.scss, CancerGov/_src/Scripts/NCI/Modules/modal/_modal.scss, CancerGov/_src/StyleSheets/nvcg.scss, CancerGov/release_notes/FEQ-february2019-backlog-release.md
Remove styling causing mobile issue with arrows in org carousel on home page.
=> Wcmsfeq 1354  homepage carousel arrows overlap tablet mobile

CancerGov/_src/StyleSheets/_nav.scss
Moved rules for section nav, mobile display after medium-down rules so mobile rule wins out in conflict with tablet/mobile rule.
Media query rules used to be in their own scss files. At some point they were moved out of that and into the same files as their non-media query rules. In this instance, it looks like moving it changed the precedence of a mobile rule with the same rule set for tablet down. This ticket moves the mobile rule for section nav top positioning in mobile below the rules for tablet down.
=> [WCMSFEQ-1348] Section menu dropdown hides under the main nav on mobile

CancerGov/_src/StyleSheets/_colors.scss, CancerGov/_src/StyleSheets/_tableSort.scss, CancerGov/release_notes/FEQ-february2019-backlog-release.md
In some tables, sorting the first column made it appear as tiles.  This was occurrring when the content in some columns exceed the height of the first.  On mobile, the height was set at 200px on mobile, which accommodated most content sizing, but still produced that funky "tiled" look. 
To correct this, the height of the first cell of the table was set to 100%, less the height of the header cell and height of the horizontal scroll bar that is generated on mobile.  The fixed height of 200px was removed from the cells of the first column, and the box shadow and other styling was added to that first cell (of the first frozen column).  In order to fully implement this fix, any sortable table with a footer (which uses the ```<tfoot>``` element) must be removed from the content.  A separate …
=> [WCMSFEQ-1303][WCMSFEQ-1338] Sortable tables fixed column

CancerGov/_src/StyleSheets/_contact.scss, CancerGov/_src/StyleSheets/_general.scss, CancerGov/release_notes/cis-contact-page.md
Change request for the behavior of the CIS links on the contact page. "Buttons" (they are actually styled links) are now to show up at all breakpoints. The only change between the breakpoints is stacking items at mobile. Previously there two sets of content, one was hidden at mobile and the other was hidden at desktop. There is now just one piece of content and the classes that were being used to hide have been removed from markup and css. Additionally, changed the html markup to use flexbox rather than the Foundation grid it was using.
https://www.cancer.gov/contact
https://www.cancer.gov/espanol/contactenos
=> Cis contact page
