- tools/build/create_branch_skeleton.job
- tools/build/setup.job
Change organization from blairlearn (test/dev) to NCIOCPL (prod)
> Point to production organization.

- tools/build/build-release.sh
- tools/build/build.sh
- tools/build/create_branch_skeleton.job
* Make the release label configurable
* Allow multiple builds to co-exist for a single branch
* Mark builds as pre-release.
> Update build to match new release process.

- CancerGov/_src/Scripts/NCI/UX/Common/Enhancements/charts.js
This is to dynamically load Highcharts and it's plug-ins.
> Updating Charts.js script to latest.

- CancerGov/_src/Scripts/NCI/Modules/bestBets/_bestBets.scss
- CancerGov/_src/StyleSheets/_colors.scss
- CancerGov/_src/StyleSheets/_home.scss
Reverted the color change for Best Bets and re-applied the requested pale blue color to the feature card.
> Revert changes for [b452d351] and re-apply. WCMSFEQ-748

- CancerGov/_src/StyleSheets/_home.scss
Merging the social media story, WCMSFEQ-824. Changed to flexbox and made social media items 2 x 2 in mobile breakpoint.
> Social media

- CancerGov/_src/StyleSheets/_general.scss
Redid margin for pullquote left and right, they now have 20px of margin top and bottom and 1em of margin to the left or right depending which way they float.
> Pullquote floated margin

- CancerGov/_src/StyleSheets/AppModuleSpecific/cts/_NCI.Delighters.scss
- CancerGov/_src/StyleSheets/_pageOptions.scss
> [WCMSFEQ-850] CTS Delighter Full width at x-small bp

- CancerGov/_src/PageTemplates/includes/TemplateIntro.inc
- CancerGov/_src/StyleSheets/nvcg.scss
- CancerGov/server/mock_views/font-loading.html
Loading fonts using google fonts api. Pointing DIN fonts to static.cancer.gov using obfuscated font and folder names specified by FontShop. This is mainly to take advantage of loading .woff2 fonts.
Please Squash and Merge.
> Fonts reloaded

- CancerGov/_src/FileAssets/Configuration/clinical-trials/OverrideMapping.txt
Updating for Sassy Snakes release on 1/31/18
> Update OverrideMapping to include trial types (DLPs break otherwise)

- CancerGov/_src/Scripts/NCI/analytics/NCIAnalyticsFunctions.js
- CancerGov/_src/Scripts/NCI/analytics/s_code.js
- CancerGov/_src/Scripts/NCI/analytics/wa_wcms_pre.js
- CancerGov/grunt/webpack.js
- CancerGov/webpack.config.js
Bringing analytic files into frontend for minification and future cleanup. Updating analyzer to analyze prod files instead of dev files for more accurate file sizes.
> [WCMSFEQ-900] Adding Analytics

- CancerGov/_src/PageTemplates/includes/TemplateIntro.inc
- CancerGov/_src/Scripts/NCI/Modules/search/_search.scss
- CancerGov/_src/StyleSheets/_fonts.scss
Fixing zoom on mobile. Reverting Montserrat back to old version because it broke the world.
> Zoom and Font corrections

- CancerGov/_src/StyleSheets/_footer.scss
We restyled the external links per client request.
> style tweeks for footer

- CancerGov/_src/Scripts/NCI/UX/PageSpecific/CTHP/CTHPPage.scss
> Merge cthp-ux-toggle

- CancerGov/_src/Scripts/NCI/UX/PageSpecific/CTHP/CTHPPage.scss
Merging 'cthp-ux-toggle' feature branch into 'cthp-ux' dev branch
> Merging 'cthp-ux-toggle' feature branch into 'cthp-ux' dev branch

- CancerGov/_src/StyleSheets/_cts-listing.scss
- CancerGov/_src/StyleSheets/_footer.scss
Hotfixes for missing styles: chat window styling and font weights for footer. WCMSFEQ-954, WCMSFEQ-970.
> Chat now styling

- CancerGov/_src/Scripts/NCI/Modules/cthpDropdown/index.scss
- CancerGov/server/mock_views/myeloproliferative.html
> [WCMSFEQ-950]

- CancerGov/_src/Scripts/NCI/Modules/cthpDropdown/index.scss
Added the tablet view breakpoint. Dropdown occurs @ 1025px and higher, as noted in the comps.
> [WCMSFEQ-949]

- CancerGov/_src/Scripts/NCI/analytics/README.md
- CancerGov/_src/StyleSheets/_cts-listing.scss
- CancerGov/_src/StyleSheets/_footer.scss
Merge latest master into cthp-ux
> Merge latest master into cthp-ux

- CancerGov/_src/Scripts/NCI/analytics/README.md
- CancerGov/_src/StyleSheets/_cts-listing.scss
- CancerGov/_src/StyleSheets/_footer.scss
Merge latest master into cthp-ux-toggle
> Merge latest master into cthp-ux-toggle

- CancerGov/_src/VelocityTemplates/BasicCTSResultsv2.vm
- Updating invalid criteria list on Results page to include new params
- Healthy Volunteers, VA only
- Merging feature branch for invalid criteria into boulevardier
> OCECTS-816, 817: Updating invalid criteria list

- CancerGov/_src/Scripts/NCI/UX/PageSpecific/CTHP/CTHPPage.scss
Merging cthp-tirs branch info cthp-ux feature branch
> Merging cthp-tirs branch info cthp-ux feature branch

- CancerGov/_src/Scripts/NCI/Modules/cthpDropdown/index.scss
- CancerGov/_src/Scripts/NCI/UX/PageSpecific/CTHP/CTHPPage.scss
- CancerGov/server/mock_views/head-and-neck.html
- CancerGov/server/mock_views/myeloproliferative.html
When resizing from Mobile to Desktop breakpoint, the drop-down does not remain aligned to the bottom of the card
- occurred due to clearfix being added via accordion js
IE11- Seeing a black background on hovering the Statistics Card on CTHP pages (Patient,HP,English,Spanish)
-bug in IE image display
> CTHP bug fixes [WCMSFEQ-985] &  [WCMSFEQ-988]

- CancerGov/_src/Scripts/NCI/Modules/bestBets/bestBets.js
Merging changes into Boulevardier branch
> Fixing broken variable passed into Best Bets definition search.

- CancerGov/_src/Scripts/NCI/Modules/cthpDropdown/index.js
- CancerGov/_src/Scripts/NCI/Modules/cthpDropdown/index.scss
Merge 'chtp-508' into 'cthp-ux'
> Merge 'chtp-508' into 'cthp-ux' 

- CancerGov/_src/StyleSheets/components/_toggle-switch.scss
> CTS - Adjusting colors

- CancerGov/_src/Scripts/NCI/UX/AppModuleSpecific/BasicCTS/Search/Enhancements/cts-field-validator.ts
- CancerGov/_src/Scripts/NCI/UX/AppModuleSpecific/BasicCTS/Search/Plugins/jquery.basicctsformtrack.js
- CancerGov/_src/StyleSheets/AppModuleSpecific/cts/_cts.advanced.scss
> [OCECTS-829] Fixing floater submit button analytics

- CancerGov/_src/Scripts/NCI/analytics/wa_wcms_pre.js
* [CGOV-6512] updated "ncidev" suite to "ncidevelopment"
* Re-added "ncienterprise" suites
> Merged "wa-suite-fix" feature branch into Master (#171)

- CancerGov/_src/Scripts/NCI/analytics/NCIAnalyticsFunctions.js
- CancerGov/_src/StyleSheets/_errorPage.scss
- CancerGov/release_notes/frontend-2018-06-06.md
* 404 pages (#173)
* NCISEO-280 - Added functionality/styling for new page not found including a english/spanish search bar in the content.
> Merge latest Master back into "wa-engagement" feature branch

- CancerGov/_src/Scripts/NCI/analytics/NCIAnalyticsFunctions.js
- CancerGov/_src/Scripts/NCI/analytics/s_code.js
Merge 'wa-en-cgovonly' into 'wa-engagement' feature branch
> Merge 'wa-en-cgovonly' into 'wa-engagement' feature branch

- CancerGov/_src/PageTemplates/includes/TemplateIntro.inc
- CancerGov/_src/Scripts/NCI/analytics/dtm-custom-code.js
- CancerGov/_src/Scripts/NCI/analytics/dtm-s_code.js
- CancerGov/_src/Scripts/NCI/analytics/wa_wcms_pre.js
Merge "dtm-meta" into "dtm-scode" feature branch
> Merge "dtm-meta" into "dtm-scode" feature branch

- CancerGov/_src/VelocityTemplates/BasicCTSPrintResultsv2.vm
- TCGA/PageTemplates/DefaultTCGAPageTemplate.aspx
- TCGA/PageTemplates/NoRightNavTCGAPageTemplate.aspx
Merged "dtm-config" into "dtm-scode" feature branch
> Merged "dtm-config" into "dtm-scode" feature branch

- CancerGov/_src/PageTemplates/includes/TemplateEnding.inc
- CancerGov/_src/PageTemplates/includes/TemplateIntro.inc
- CancerGov/_src/Scripts/NCI/analytics/README.md
- CancerGov/release_notes/wa-engagement.md
- DCEG/PageTemplates/DefaultGeneralTemplate-NoSidebars.aspx
- DCEG/PageTemplates/DefaultGeneralTemplate.aspx
- DCEG/PageTemplates/DefaultHomeTemplate.aspx
- DCEG/PageTemplates/DefaultLandingTemplate.aspx
- DCEG/PageTemplates/GeneralTemplate-NoRightSidebar.aspx
- TCGA/PageTemplates/DefaultTCGAPageTemplate.aspx
- TCGA/PageTemplates/NoRightNavTCGAPageTemplate.aspx
Merged "dtm-perc" into "dtm-scode" feature branch
> Merged "dtm-perc" into "dtm-scode" feature branch 

- CancerGov/_src/StyleSheets/_tableSort.scss
- CancerGov/server/mock_views/research-funding.html
- CancerGov/server/mock_views/special-sources.html
- CancerGov/server/mock_views/training-at-nci.html
Merged latest master into "dtm-scode" feature branch
> Merged latest master into "dtm-scode" feature branch

- CancerGov/_src/Scripts/NCI/analytics/README.md
* Updated README.md:
** Added AppMeasurement instructions
** Updated rule names
> Merged "wa-cleanup" into "dtm-scode" feature branch

- CancerGov/_src/StyleSheets/_homelanding.scss
the content for the third guide card ("Find a Cancer Type") was approved and placed on Percussion, hence we no longer need to ignore this card.
> [WCMSFEQ-1028] Apply realignment to all three homepage guide cards

- CancerGov/release_notes/frontend-2018-07-20-july-sprint.md
- DCEG/Stylesheets/layout-print.css
> WCMSFEQ-1071 - changed default print font size to 16px.

- CancerGov/_src/StyleSheets/_header.scss
Fix for style selectors that were removed with modernizr
> [WCMSFEQ 1078] modernizr css fix

- CancerGov/_src/PageTemplates/NVCGJSAppModulePageTemplate.aspx
- CancerGov/_src/PageTemplates/includes/PageOptions-JSAppModule.inc
* Implemented new JavaScript App Module Page Template
> Merged lasted Master into "dtm-cde" feature branch

- CancerGov/_src/Scripts/NCI/UX/PageSpecific/Inner/Enhancements/directory-search-results.js
Links were removed for potential 508 compliance issues. Until full requirements can be determined, previous functionality is being restored.
> FIXUP [WCMSFEQ-931] Reenable genetics directory links

- .gitignore
- CancerGov/package-lock.json
- CancerGov/release_notes/frontend-2018-08-22-august-sprint.md
Begin tracking package-lock.json for better out of the box dependency management.
> [WCMSFEQ-1087]  Track package-lock.json

- CancerGov/_src/Scripts/NCI/analytics/s_code.js
- CancerGov/release_notes/frontend-2018-08-22-august-sprint.md
* [WCMSFEQ-1030] reduce flt timeout to 625
* Added new meta tag functions
* Added DTM to CTS print velocity template
* Added prop/eVar44 (group)
* Merged "dtm-cleanup" into "dtm-cde" feature branch (#216)
* Reverted AnalyticsControl ID, BasicCTSPrintResultsv2.vm, package.json
* Removed new (post-DTM) s.prop values from s_code.js
* Renamed "dtm-cde" branch to "wcmsfeq-1099"
> [WCMSFEQ-1099] Updates to s_code

- CancerGov/_src/Scripts/NCI/Modules/floatingDelighter/delighters/index.js
- CancerGov/_src/Scripts/NCI/Modules/floatingDelighter/delighters/nciConnect/index.js
- CancerGov/_src/Scripts/NCI/Modules/floatingDelighter/delighters/nciConnect/index.scss
- CancerGov/_src/Scripts/NCI/Modules/floatingDelighter/rules.js
Delighter added for NCI Connect section.
> Nci connect delighter

- CancerGov/_src/Scripts/NCI/Modules/bestBets/bestBets.js
- CancerGov/release_notes/frontend-2018-08-22-august-sprint.md
> [WCMSFEQ-1100]  Update bestBets.js to use 'exact' search type for Dictionary.search

- CancerGov/_src/Widgets/Term Dictionary/css/widget.css
- CancerGov/release_notes/frontend-2018-september-sprint.md
Changed color of dicitionary widget's search bar background color and widgets border top color for 508 color contrast requirements. New color is purple.
> [WCMSFEQ-1153] - Update Dictionary Widget Search Button contrast for 508

- CancerGov/_src/Scripts/NCI/UX/AppModuleSpecific/R4R/R4R.js
* WCMSFEQ-1183: Adding redirect for specific URLs.
- Need to do this the hacky way in here, since the redirect map doesn't work with push state.
* WCMSFEQ-1183: Updating redirects for R4R pages.
* WCMSFEQ-1183: Removing unneeded redirect-check code and console logs.
> Merge latest master into "dtm" branch

- CancerGov/_src/Scripts/NCI/UX/Common/Enhancements/charts.js
- CancerGov/_src/StyleSheets/_jqueryui.scss
- CancerGov/_src/StyleSheets/_tables.scss
- CancerGov/server/mock_views/highmaps.html
Adding support for Highmaps to be used on Factbook pages
Updated charts.js to support offline exporting. Few other minor CSS tweeks to improve UI interaction
> [WCMSFEQ-1043] Highmaps Support

- CancerGov/_src/Scripts/NCI/UX/PageSpecific/Inner/InnerPage.scss
- CancerGov/_src/StyleSheets/_related-links.scss
- CancerGov/server/mock_views/Related_Links.html
Adding styles for future DCEG related links module. There may or may not be HTML markup changes prior to migration so two style blocks are included. Placing these styles in InnerPage for now.
> [WCMSFEQ-1188] DCEG Related Links

- CancerGov/_src/Scripts/NCI/UX/AppModuleSpecific/R4R/config/cancer_gov/r4r_cgov_glue.scss
- CancerGov/_src/Scripts/NCI/UX/AppModuleSpecific/R4R/config/index.js
- CancerGov/package-lock.json
- CancerGov/package.json
- CancerGov/release_notes/WCMSRR-223__r4r-design-tweaks.md
This release is for basic design tweaks. The bulk of the changes occured as part of an r4r update and this is only to update the FEQ r4r dependency. One change was made locally, to remove the custom override of a link which caused it to be displayed as a cgov arrow link.
> [WCMSRR-223]  R4R Design Tweaks

- CancerGov/_src/Scripts/NCI/Modules/modal/_modal.scss
- CancerGov/_src/Scripts/NCI/UX/Common/Enhancements/analytics.js
- CancerGov/_src/Scripts/NCI/UX/Common/Enhancements/popup_functions.js
- CancerGov/_src/Scripts/NCI/analytics/nci-analytics-functions.js
An adjustment for modal definition titles
An adjustment for analytic clicks on blog pages
> QA feedback round 2

- CancerGov/_src/Scripts/NCI/UX/PageSpecific/PDQ/PDQPage.scss
Add top margin to all h2 (On This Page) sections except the first
Hide 'In this Section' nav on mobile
> [WCMSFEQ-1340]  Add padding to PDQ h2 sections

- CancerGov/_src/Scripts/NCI/analytics/nci-analytics-functions.js
update prop67 to 'D=pageName' for redesigned PDQ analytics
> [WMCSFEQ-1272]  Analytics for updated PDQ navigation

- CancerGov/_src/Scripts/NCI/UX/Common/Enhancements/charts.js
- CancerGov/release_notes/FEQ-february2019-backlog-release.md
> Wcmsfeq 1323  highchart label change
